# Generated by Django 3.0.8 on 2020-07-07 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_history', '0002_auto_20200706_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale_record',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_history.Customer'),
        ),
        migrations.AlterField(
            model_name='sale_record',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_history.Item'),
        ),
    ]
